### ISSUE TITLE
Silent install

### ISSUE THREAD

**Issue by james-s-nduka** [NearlyUnique/awsSts#3]
Would be great to have the ability of obtaining the credentials (printing out the stdout?) without the need for prompts in selecting a role. Would be ideal in CI/CD situations where information is required dynamically

**Comment by NearlyUnique** [comment]
-- role option s is now possible as of 0.6

What would the outputs look like?
```
#> awsSts --role blah
aws_access_key_id=some-value<new-line>
aws_secret_access_key=some-value<new-line>
aws_session_token=some-value<new-line>
`````

**Comment by NearlyUnique** [comment]
session key can be written to stdout and role can be pre selected
